
set(IE_ROOT_DIR ${ROOT_DIR}/3rd/openvino)
set(IE_BIN_DIR ${IE_ROOT_DIR}/bin/intel64/Release)
set(IE_THREADING "OMP" CACHE STRING "Set threading mode for IE: TBB / OMP / SEQ")

set(IE_BIN_LIBS
	${IE_BIN_DIR}/libopenvino_intel_cpu_plugin.so
	${IE_BIN_DIR}/libopenvino_ir_frontend.so
	${IE_BIN_DIR}/libopenvino_onnx_frontend.so
	${IE_BIN_DIR}/libopenvino.so)

set(IE_BUILD_OPTIONS 
	-DCMAKE_BUILD_TYPE="Release"
	-DCMAKE_CXX_FLAGS="-Wno-attributes"
	-DTREAT_WARNING_AS_ERROR=OFF
	-DENABLE_SANITIZER=OFF
	-DOS_FOLDER=OFF
	-DENABLE_TESTS=OFF
	-DENABLE_BEH_TESTS=OFF
	-DENABLE_FUNCTIONAL_TESTS=OFF
	-DENABLE_CPPLINT=OFF
	-DENABLE_PROFILING_ITT=OFF
	-DENABLE_SAMPLES=OFF
	-DENABLE_SEGMENTATION_TESTS=OFF
	-DENABLE_OBJECT_DETECTION_TESTS=OFF
	-DVERBOSE_BUILD=OFF
	-DENABLE_IR_READER=ON
	-DHAVE_CPUID_INFO=OFF
	-DENABLE_AVX512F=${SIMD_AVX512}
	-DENABLE_AVX2=ON
	-DENABLE_SSE42=ON
	-DTHREADING_DEFAULT=${IE_THREADING}
	-DENABLE_INTEL_GPU=OFF
	-DENABLE_ONEDNN_FOR_GPU=OFF
	-DENABLE_INTEL_NPU=OFF
	-DENABLE_OV_TF_LITE_FRONTEND=OFF
	-DENABLE_OV_TF_FRONTEND=OFF
	-DENABLE_OV_PADDLE_FRONTEND=OFF
	-DENABLE_OV_PYTORCH_FRONTEND=OFF
	-DENABLE_OV_JAX_FRONTEND=OFF
	-DENABLE_LIBRARY_VERSIONING=OFF
	)

file(MAKE_DIRECTORY ${IE_ROOT_DIR}/build)
add_custom_command(
	OUTPUT ${IE_BIN_LIBS}
	COMMAND cmake .. ${IE_BUILD_OPTIONS} && make -j16
	COMMAND ${CMAKE_COMMAND} -E copy ${IE_BIN_LIBS} ${CMAKE_BINARY_DIR} 
	WORKING_DIRECTORY ${IE_ROOT_DIR}/build)
	

add_custom_target(make_openvino DEPENDS ${IE_BIN_LIBS})

include_directories(${IE_ROOT_DIR}/src/inference/include)
include_directories(${IE_ROOT_DIR}/src/core/include)

