cmake_minimum_required(VERSION 3.7)

set(SIMD_TEST OFF CACHE BOOL "" FORCE)
set(SIMD_SHARED ON CACHE BOOL "" FORCE)
set(SIMD_GET_VERSION ON CACHE BOOL "" FORCE)
set(SIMD_TOOLCHAIN ${CMAKE_CXX_COMPILER})
set(SIMD_INFO ${SYNET_INFO} CACHE BOOL "" FORCE)
set(SIMD_SYNET ON CACHE BOOL "" FORCE)
set(SIMD_INT8_DEBUG OFF CACHE BOOL "" FORCE)
set(SIMD_LIB "Simd")	
if(PERF_STAT GREATER_EQUAL 2)
	set(SIMD_PERF ON CACHE BOOL "" FORCE)
else()
	set(SIMD_PERF OFF CACHE BOOL "" FORCE)
endif()
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})

list(APPEND SYNET_DEFINITIONS -DSYNET_SIMD_LIBRARY_ENABLE)

add_subdirectory(${ROOT_DIR}/3rd/Simd/prj/cmake 3rd/Simd)

include_directories(${ROOT_DIR}/3rd/Simd/src)
