if((SYNET_TEST STREQUAL "inference_engine") OR (SYNET_TEST STREQUAL "all"))
	include(${ROOT_DIR}/prj/cmake/openvino.cmake)
	file(GLOB_RECURSE TEST_IE_SRC ${ROOT_DIR}/src/Test/TestInferenceEngine.cpp)
	set_source_files_properties(${TEST_IE_SRC} PROPERTIES COMPILE_FLAGS "${COMMON_CXX_FLAGS}")
	add_executable(test_inference_engine ${TEST_IE_SRC})
	add_dependencies(test_inference_engine make_openvino)
	target_compile_definitions(test_inference_engine PUBLIC ${SYNET_DEFINITIONS})
	target_link_libraries(test_inference_engine ${IE_BIN_LIBS} ${SIMD_LIB} Synet CvtCore -ldl -lpthread)
endif()

if((SYNET_TEST STREQUAL "onnx") OR (SYNET_TEST STREQUAL "all"))
	file(GLOB_RECURSE TEST_ONNX_SRC ${ROOT_DIR}/src/Test/TestOnnx.cpp)
	set_source_files_properties(${TEST_ONNX_SRC} PROPERTIES COMPILE_FLAGS "${COMMON_CXX_FLAGS}")
	add_executable(test_onnx ${TEST_ONNX_SRC})
	include(${ROOT_DIR}/prj/cmake/onnxruntime.cmake)
	include(${ROOT_DIR}/prj/cmake/CvtOnnx.cmake)
	target_compile_definitions(test_onnx PUBLIC -DSYNET_ONNXRUNTIME_ENABLE ${SYNET_DEFINITIONS})
	target_include_directories(test_onnx PUBLIC ${ORT_INCS})
	target_link_libraries(test_onnx ${ORT_LIBS} ${SIMD_LIB} Synet CvtCore CvtOnnx -ldl -lpthread)
endif()

if((SYNET_TEST STREQUAL "performance_difference") OR (SYNET_TEST STREQUAL "all"))	
	file(GLOB_RECURSE PERF_DIFF_SRC ${ROOT_DIR}/src/Test/TestPerformanceDifference.cpp)
	set_source_files_properties(${PERF_DIFF_SRC} PROPERTIES COMPILE_FLAGS "${COMMON_CXX_FLAGS}")
	add_executable(test_performance_difference ${PERF_DIFF_SRC})
	target_compile_definitions(test_performance_difference PUBLIC ${SYNET_DEFINITIONS})
	target_link_libraries(test_performance_difference ${SIMD_LIB} Synet -ldl -lpthread -pthread)
endif()

if((SYNET_TEST STREQUAL "precision") OR (SYNET_TEST STREQUAL "all"))	
	if (SYNET_TEST STREQUAL "precision")
		include(${ROOT_DIR}/prj/cmake/inference-engine.cmake)
	endif()
	file(GLOB_RECURSE PRECISION_SRC ${ROOT_DIR}/src/Test/TestPrecision.cpp)
	set_source_files_properties(${PRECISION_SRC} PROPERTIES COMPILE_FLAGS "${COMMON_CXX_FLAGS}")
	add_executable(test_precision ${PRECISION_SRC})
	add_dependencies(test_precision make_openvino)
	target_compile_definitions(test_precision PUBLIC ${SYNET_DEFINITIONS})
	target_link_libraries(test_precision ${IE_BIN_LIBS} ${SIMD_LIB} Synet -ldl -lpthread)
endif()

if((SYNET_TEST STREQUAL "quantization") OR (SYNET_TEST STREQUAL "all"))	
	file(GLOB_RECURSE QUANTIZATION_SRC ${ROOT_DIR}/src/Test/TestQuantization.cpp)
	set_source_files_properties(${QUANTIZATION_SRC} PROPERTIES COMPILE_FLAGS "${COMMON_CXX_FLAGS}")
	add_executable(test_quantization ${QUANTIZATION_SRC})
	target_compile_definitions(test_quantization PUBLIC ${SYNET_DEFINITIONS})
	target_link_libraries(test_quantization ${SIMD_LIB} Synet CvtCore -ldl -lpthread)
endif()

if((SYNET_TEST STREQUAL "stability") OR (SYNET_TEST STREQUAL "all"))
	file(GLOB_RECURSE STABILITY_SRC ${ROOT_DIR}/src/Test/TestStability.cpp)
	set_source_files_properties(${STABILITY_SRC} PROPERTIES COMPILE_FLAGS "${COMMON_CXX_FLAGS}")
	add_executable(test_stability ${STABILITY_SRC})
	target_compile_definitions(test_stability PUBLIC ${SYNET_DEFINITIONS})
	target_link_libraries(test_stability ${SIMD_LIB} Synet -ldl -lpthread)
endif()

if((SYNET_TEST STREQUAL "optimizer") OR (SYNET_TEST STREQUAL "all"))	
	file(GLOB_RECURSE OPTIMIZER_SRC ${ROOT_DIR}/src/Test/TestOptimizer.cpp)
	set_source_files_properties(${OPTIMIZER_SRC} PROPERTIES COMPILE_FLAGS "${COMMON_CXX_FLAGS}")
	add_executable(test_optimizer ${OPTIMIZER_SRC})
	target_compile_definitions(test_optimizer PUBLIC ${SYNET_DEFINITIONS})
	target_link_libraries(test_optimizer ${SIMD_LIB} Synet CvtCore -ldl -lpthread)
endif()

if((SYNET_TEST STREQUAL "bf16") OR (SYNET_TEST STREQUAL "all"))	
	file(GLOB_RECURSE BF16_SRC ${ROOT_DIR}/src/Test/TestBf16.cpp)
	set_source_files_properties(${BF16_SRC} PROPERTIES COMPILE_FLAGS "${COMMON_CXX_FLAGS}")
	add_executable(test_bf16 ${BF16_SRC})
	target_compile_definitions(test_bf16 PUBLIC ${SYNET_DEFINITIONS})
	target_link_libraries(test_bf16 ${SIMD_LIB} Synet CvtCore -ldl -lpthread)
endif()

if((SYNET_TEST STREQUAL "multi_threads") OR (SYNET_TEST STREQUAL "all"))	
	file(GLOB_RECURSE TMT_SRC ${ROOT_DIR}/src/Test/TestMultiThreads.cpp)
	set_source_files_properties(${TMT_SRC} PROPERTIES COMPILE_FLAGS "${COMMON_CXX_FLAGS}")
	add_executable(test_multi_threads ${TMT_SRC})
	target_compile_definitions(test_multi_threads PUBLIC ${SYNET_DEFINITIONS})
	target_link_libraries(test_multi_threads ${SIMD_LIB} Synet -ldl -lpthread)
endif()

if((SYNET_TEST STREQUAL "video") OR (SYNET_TEST STREQUAL "all"))
	file(GLOB_RECURSE TV_SRC ${ROOT_DIR}/src/Test/TestVideo.cpp)
	set_source_files_properties(${TV_SRC} PROPERTIES COMPILE_FLAGS "${COMMON_CXX_FLAGS}")
	add_executable(test_video ${TV_SRC})
	target_compile_definitions(test_video PUBLIC ${SYNET_DEFINITIONS})
	target_link_libraries(test_video ${SIMD_LIB} Synet -ldl -lpthread)
	if(SYNET_OPENCV)
		find_package(OpenCV REQUIRED)
		target_compile_definitions(test_video PUBLIC SYNET_OPENCV_ENABLE)
		target_link_libraries(test_video ${OpenCV_LIBS})
		target_include_directories(test_video PUBLIC ${OpenCV_INCLUDE_DIRS})
	endif()
endif()

